{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.tooltipoverhaul",
    "module": "tooltipoverhaul-neoforge-1.21.1",
    "version": "2.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tooltipoverhaul-neoforge-1.21.1-2.0.5.jar",
          "url": "tooltipoverhaul-neoforge-1.21.1-2.0.5.jar",
          "size": 916395,
          "sha512": "24f39e52c105e13356c8d082b881037b0309f49f2a7dbfaef67a6dd859471f8eeef487df49507c65c9186b483da1473810b252a3eb288e0ee91199252b44e407",
          "sha256": "784767f10f104595657cd312d410c87432bd766fdd073547286b89912aa83241",
          "sha1": "21b8e1af070cba67f0ad904d87ad82f576cde08a",
          "md5": "2b079359dff6ebcb109043c009b8d1c8"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-neoforge-1.21.1",
          "version": "2.0.5"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "2.0.5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "apotheosis-313970",
          "version": {
            "requires": "6926309"
          }
        },
        {
          "group": "curse.maven",
          "module": "apothic-attributes-898963",
          "version": {
            "requires": "6751650"
          }
        },
        {
          "group": "curse.maven",
          "module": "apothic-spawners-986583",
          "version": {
            "requires": "6751589"
          }
        },
        {
          "group": "curse.maven",
          "module": "apothic-enchanting-1063926",
          "version": {
            "requires": "6926290"
          }
        },
        {
          "group": "curse.maven",
          "module": "patchouli-306770",
          "version": {
            "requires": "6842247"
          }
        },
        {
          "group": "curse.maven",
          "module": "placebo-283644",
          "version": {
            "requires": "6926281"
          }
        },
        {
          "group": "curse.maven",
          "module": "lendercataclysm-551586",
          "version": {
            "requires": "6906997"
          }
        },
        {
          "group": "curse.maven",
          "module": "curios-309927",
          "version": {
            "requires": "6529130"
          }
        },
        {
          "group": "curse.maven",
          "module": "lionfish-api-1001614",
          "version": {
            "requires": "6168249"
          }
        },
        {
          "group": "curse.maven",
          "module": "metal-bundles-891325",
          "version": {
            "requires": "6697871"
          }
        },
        {
          "group": "curse.maven",
          "module": "puzzles-lib-495476",
          "version": {
            "requires": "7140307"
          }
        },
        {
          "group": "curse.maven",
          "module": "oracle-index-1206582",
          "version": {
            "requires": "7773037"
          }
        },
        {
          "group": "curse.maven",
          "module": "architectury-api-419699",
          "version": {
            "requires": "5786327"
          }
        },
        {
          "group": "curse.maven",
          "module": "owo-lib-532610",
          "version": {
            "requires": "6785734"
          }
        },
        {
          "group": "curse.maven",
          "module": "oritech-1030830",
          "version": {
            "requires": "7786123"
          }
        },
        {
          "group": "curse.maven",
          "module": "athena-841890",
          "version": {
            "requires": "6669522"
          }
        },
        {
          "group": "curse.maven",
          "module": "geckolib-388172",
          "version": {
            "requires": "7707149"
          }
        },
        {
          "group": "curse.maven",
          "module": "itemzoom-261725",
          "version": {
            "requires": "5536959"
          }
        },
        {
          "group": "curse.maven",
          "module": "tough-as-nails-246391",
          "version": {
            "requires": "5833252"
          }
        },
        {
          "group": "curse.maven",
          "module": "glitchcore-955399",
          "version": {
            "requires": "8109792"
          }
        },
        {
          "group": "curse.maven",
          "module": "jei-238222",
          "version": {
            "requires": "8358264"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "7509726"
          }
        }
      ],
      "files": [
        {
          "name": "tooltipoverhaul-neoforge-1.21.1-2.0.5.jar",
          "url": "tooltipoverhaul-neoforge-1.21.1-2.0.5.jar",
          "size": 916395,
          "sha512": "24f39e52c105e13356c8d082b881037b0309f49f2a7dbfaef67a6dd859471f8eeef487df49507c65c9186b483da1473810b252a3eb288e0ee91199252b44e407",
          "sha256": "784767f10f104595657cd312d410c87432bd766fdd073547286b89912aa83241",
          "sha1": "21b8e1af070cba67f0ad904d87ad82f576cde08a",
          "md5": "2b079359dff6ebcb109043c009b8d1c8"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-neoforge-1.21.1",
          "version": "2.0.5"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "2.0.5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-neoforge-1.21.1-2.0.5-sources.jar",
          "url": "tooltipoverhaul-neoforge-1.21.1-2.0.5-sources.jar",
          "size": 528917,
          "sha512": "7453024e0fec13b15b5f3171cade5fab4486eec0dc15d86d58cf6e856da54a353e276fe7006748d96416db532d1c85615d57512f2d66785f040b86d39b15e18e",
          "sha256": "92aebad4553ecd04ac6da31be9cf2fd261cc31120dce404ebcd377c966967d1e",
          "sha1": "2031bbb2b561b4adc2c46628bdb49d7c386b6f81",
          "md5": "aafd9a34ca6b705cff8e4380acf6e9b1"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-neoforge-1.21.1",
          "version": "2.0.5"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "2.0.5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-neoforge-1.21.1-2.0.5-javadoc.jar",
          "url": "tooltipoverhaul-neoforge-1.21.1-2.0.5-javadoc.jar",
          "size": 906953,
          "sha512": "be8292c8ea6656d20dbeb7b90fe83ebb8668484882b5f339fb80dc11f192b66406aeb11ba1f7c748f54988ef81c6838076df4ac36e5c2614957a423a6e441b1b",
          "sha256": "9af808b62e55d81d3860f7d97d1a0a2b5faccda865fdac0a3c0b86cc07165520",
          "sha1": "6c8addd024461db04bd9ebe6f701538dbe26ea9c",
          "md5": "bd7b66cf201a5dcc74e642d3ab3f927a"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-neoforge-1.21.1",
          "version": "2.0.5"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "2.0.5"
        }
      ]
    }
  ]
}
