{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-common-1.20.1",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.3.0.jar",
          "url": "knightlib-common-1.20.1-1.3.0.jar",
          "size": 106002,
          "sha512": "9fe2bd611f54f69dd608d172e5b4a382157a68b0b4e593d0ebddb046e9a42f7411c88463efc92c0406fdf2982e7a86f40ea3ba74b2ec913188e078a860a97be7",
          "sha256": "d0136b620bd6f259da6919640e9ad60fcf52acf040c8788f346f6300bc116cdb",
          "sha1": "4e514f507db38d2f6dc78780c943e0d69391b153",
          "md5": "e3612709948d415a3178725fab5f55f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.3.0.jar",
          "url": "knightlib-common-1.20.1-1.3.0.jar",
          "size": 106002,
          "sha512": "9fe2bd611f54f69dd608d172e5b4a382157a68b0b4e593d0ebddb046e9a42f7411c88463efc92c0406fdf2982e7a86f40ea3ba74b2ec913188e078a860a97be7",
          "sha256": "d0136b620bd6f259da6919640e9ad60fcf52acf040c8788f346f6300bc116cdb",
          "sha1": "4e514f507db38d2f6dc78780c943e0d69391b153",
          "md5": "e3612709948d415a3178725fab5f55f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.3.0-sources.jar",
          "url": "knightlib-common-1.20.1-1.3.0-sources.jar",
          "size": 86706,
          "sha512": "098294bded1cbcb38049cd5de45ddd06eeb4e6e987d9c0271f1dae2f153d7699a9aba1b9d6ff914855622b871836a14b4c0ab7d54c0613497eab3e18abb3d2ea",
          "sha256": "67954231f51c99cd2df474bc24c64bfc63fbedec95b240100fbc5fd51c2e7126",
          "sha1": "c74f6462cbf134bf9c4e5e2f14f203776e0232a9",
          "md5": "e431fd631ee300763e25993f6f1e8f62"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.3.0-javadoc.jar",
          "url": "knightlib-common-1.20.1-1.3.0-javadoc.jar",
          "size": 214324,
          "sha512": "853b0bd9ec87da82597407086b6f64f596a255f4fb826d6befebdd5c88e8730708ae9690a526bf81a45ff95f0d35198fff940eff8e1af4cec4c6b539d0a41c9f",
          "sha256": "62ac4a1ebcf4d2c63b9dcc7367e15d36a06c53ae6c97344a30ce0e9325de5c56",
          "sha1": "dc7d918e1c003c9f6fcc8735e1c1d7c43b0c183a",
          "md5": "abf4264277e31fad2d59592a7d37f3a8"
        }
      ]
    }
  ]
}
