{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-common-1.20.1",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.3.0.jar",
          "url": "knightlib-common-1.20.1-1.3.0.jar",
          "size": 105874,
          "sha512": "cfa02ddd6c6c943ee68de06e0e0f821a20e3bc0bd66302d6fa343c5f350047db55d9a1e98cf45a5c5eae6b598053bced288f8573669a59f8f9a727410a7aa576",
          "sha256": "28bb2f9377e85218ac2f3b43522d425383f0612a84183f4a0450ac31d5bd1bb1",
          "sha1": "5708600c37ca15ac5b41cb96c827f1b226913d99",
          "md5": "029898d9739f9979d35fd45fb28de3a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.3.0.jar",
          "url": "knightlib-common-1.20.1-1.3.0.jar",
          "size": 105874,
          "sha512": "cfa02ddd6c6c943ee68de06e0e0f821a20e3bc0bd66302d6fa343c5f350047db55d9a1e98cf45a5c5eae6b598053bced288f8573669a59f8f9a727410a7aa576",
          "sha256": "28bb2f9377e85218ac2f3b43522d425383f0612a84183f4a0450ac31d5bd1bb1",
          "sha1": "5708600c37ca15ac5b41cb96c827f1b226913d99",
          "md5": "029898d9739f9979d35fd45fb28de3a2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.3.0-sources.jar",
          "url": "knightlib-common-1.20.1-1.3.0-sources.jar",
          "size": 86506,
          "sha512": "0e6a3108a692982831d339b97708bda1a84e620ec27fa0c6a0abfb639e343ef4c5b0ab81b6ce6e3f32dfa1d435834d4eedb8f1667726c693d01e5738baf26dc1",
          "sha256": "6ce276c2c4c9b8cebd18747e5547c55d86311b8b2b32b5ea625289763bd57f48",
          "sha1": "77ede79f0973afa642d108685da06cd10295fe19",
          "md5": "36068c4b185d239182200f2fe37f8f47"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.3.0-javadoc.jar",
          "url": "knightlib-common-1.20.1-1.3.0-javadoc.jar",
          "size": 214316,
          "sha512": "2097e96d1d0597a50e90080370afe7159074afb75ad2422589909c4317ace21052a007a769535df6771f914b288ec464cb11dea3d3972c2707b9f525ed3ca33e",
          "sha256": "ad5d4601b3fa15624952abee235b12aba3007b702e6cfd6a0eee21533a8d971b",
          "sha1": "e8fd2edbfd6281e0eaea51a2f0c13b890f805050",
          "md5": "2bfb3d00f8db596d3c55d26c5aafde1f"
        }
      ]
    }
  ]
}
