{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.tooltipoverhaul",
    "module": "tooltipoverhaul-forge-1.20.1",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-forge-1.20.1-2.0.0-sources.jar",
          "url": "tooltipoverhaul-forge-1.20.1-2.0.0-sources.jar",
          "size": 517560,
          "sha512": "0e7234dd0c9a8909fbd838fbdb244f874b8b3df749a656a14dd28e26b85a6bb2437e9f646039bea9de3a5f00700afe440f8498a317f039824dd825e028e613bc",
          "sha256": "4bb93bd6e06a74e6278a12cd950aea2e73938ef65aeb317436664087af1da7d6",
          "sha1": "825727ea348c6a9453c6cce061c775cbf7ab2883",
          "md5": "b90156032e7b8be0a3d66a4291525bb7"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-forge-1.20.1",
          "version": "2.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "2.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "forge",
          "version": "2.0.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-forge-1.20.1-2.0.0-javadoc.jar",
          "url": "tooltipoverhaul-forge-1.20.1-2.0.0-javadoc.jar",
          "size": 870431,
          "sha512": "aaadd6a32c06ccf1c5443d39586552bf75b68e6c17cfc9bae5da8fc1cfd3fe46bcbcfb63ba45254d94ea8518a6073b24f3971063097428b0004578b3d50f4308",
          "sha256": "fc8362f1c1be147aed823ea3e2013e49ae9d80da2a857ee514b244b1446fb6f9",
          "sha1": "e0f9f3b42cc56ea08417ffe6ea88cd1aa09fe2d1",
          "md5": "ded5cad79589b0ec63c429e9a2a385af"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-forge-1.20.1",
          "version": "2.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "2.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "forge",
          "version": "2.0.0"
        }
      ]
    },
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-forge-1.20.1-2.0.0.jar",
          "url": "tooltipoverhaul-forge-1.20.1-2.0.0.jar",
          "size": 903677,
          "sha512": "9d6a42d1fe0483764cc42e6998fc735dad5abb7e1cc68b01ac7d57c026014a2ae3446bb8e6d1bd3af44926a673613e796972c1ba02448979d2f81e166e3d8151",
          "sha256": "cbb3e30753ce9819f572de35fbb8f1c57dc7d77b2969da7c2db42c664df5bea0",
          "sha1": "3203c58fda92da8de886b4b3ff547266f099e8fb",
          "md5": "4003de00302f4fbe4d186c5d2c6e57dd"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tooltipoverhaul-forge-1.20.1-2.0.0.jar",
          "url": "tooltipoverhaul-forge-1.20.1-2.0.0.jar",
          "size": 903677,
          "sha512": "9d6a42d1fe0483764cc42e6998fc735dad5abb7e1cc68b01ac7d57c026014a2ae3446bb8e6d1bd3af44926a673613e796972c1ba02448979d2f81e166e3d8151",
          "sha256": "cbb3e30753ce9819f572de35fbb8f1c57dc7d77b2969da7c2db42c664df5bea0",
          "sha1": "3203c58fda92da8de886b4b3ff547266f099e8fb",
          "md5": "4003de00302f4fbe4d186c5d2c6e57dd"
        }
      ]
    }
  ]
}
