{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-common-1.20.1",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.4.0.jar",
          "url": "knightlib-common-1.20.1-1.4.0.jar",
          "size": 179445,
          "sha512": "19ce32dceff88bf17e6bb98dbe97844a06e99701ea70efcf1fe039ad1de8d3c64bf0b1c3c94f77473150ee11aaf71d103615dbcca732bde4cb8096dff61aad78",
          "sha256": "6d1a06a53bc93ff53ae4078e0a8a42597528281f1f0569c4feeafbec7b7f8459",
          "sha1": "e07a0728f556954a46d653cf85f5fad8ef601497",
          "md5": "f5c77d3e35485f596efee0a42a58c839"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.4.0.jar",
          "url": "knightlib-common-1.20.1-1.4.0.jar",
          "size": 179445,
          "sha512": "19ce32dceff88bf17e6bb98dbe97844a06e99701ea70efcf1fe039ad1de8d3c64bf0b1c3c94f77473150ee11aaf71d103615dbcca732bde4cb8096dff61aad78",
          "sha256": "6d1a06a53bc93ff53ae4078e0a8a42597528281f1f0569c4feeafbec7b7f8459",
          "sha1": "e07a0728f556954a46d653cf85f5fad8ef601497",
          "md5": "f5c77d3e35485f596efee0a42a58c839"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.4.0-sources.jar",
          "url": "knightlib-common-1.20.1-1.4.0-sources.jar",
          "size": 126364,
          "sha512": "a8a524156f6c9450187d11cab0f47fe3237077c161a393d7a6da4a9bb0f16cd240f743be42241592073528fe839377b1669117b52c2f36488c37ea00ff7504ad",
          "sha256": "c87c7d3443cc5274dc2dee1be77fc564a55cabb717ce67ff228bdb5aed385d0f",
          "sha1": "26fd64be74e8ac03078fe24d76a88763649f94cd",
          "md5": "433336eb1e64dbedcafb961eed7b0fc1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.4.0-javadoc.jar",
          "url": "knightlib-common-1.20.1-1.4.0-javadoc.jar",
          "size": 425550,
          "sha512": "c53f86321625721fb122df7e76c9456b3af0b80f7cfd58897ece5681e494d788024f89eed25702bd15cb8e4d36de0d4cff166b44b186dfb2de156882c7510883",
          "sha256": "339f9396ed4f9a90a5a1b52538811d74fe0139d871c4fb5ac8e6e895a424203d",
          "sha1": "0e7f6c07be1f7e7a4f550db6bfcf06e203550d54",
          "md5": "5388f60876d52773d2257dc52d0d32cc"
        }
      ]
    }
  ]
}
