{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-common-1.20.1",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.4.0.jar",
          "url": "knightlib-common-1.20.1-1.4.0.jar",
          "size": 179447,
          "sha512": "f2f0f59e550df46aaa027519050449c8dbe3d5c2e3e727e2a99cd0615311654b28cd196b84b02e1bcf8de7b78cf6b43dbbc864ee03dcfa371d7f5fd39704a617",
          "sha256": "6d1e2858b2057518aee16d92e3030da7acf250bd36fb4bb4e253273ff06f9913",
          "sha1": "73bb4f158b142759718698a4617f4a239f56dc13",
          "md5": "33fb38a561830458932a452dc6eab582"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.4.0.jar",
          "url": "knightlib-common-1.20.1-1.4.0.jar",
          "size": 179447,
          "sha512": "f2f0f59e550df46aaa027519050449c8dbe3d5c2e3e727e2a99cd0615311654b28cd196b84b02e1bcf8de7b78cf6b43dbbc864ee03dcfa371d7f5fd39704a617",
          "sha256": "6d1e2858b2057518aee16d92e3030da7acf250bd36fb4bb4e253273ff06f9913",
          "sha1": "73bb4f158b142759718698a4617f4a239f56dc13",
          "md5": "33fb38a561830458932a452dc6eab582"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.4.0-sources.jar",
          "url": "knightlib-common-1.20.1-1.4.0-sources.jar",
          "size": 126364,
          "sha512": "bab70d55c72def9693435d7e58217b8c401978aead3c8675d8c86e548ba1a6b12240db079e19cb2150d0beecb61fca2e47ee7aa12d62bf948bf721b9c2532848",
          "sha256": "300ee53e71c4c64f7881f13b8aff9d101d7ccd9f8a4d4aadc464337ae246b885",
          "sha1": "86f34047bc57dc4e03ab8694aca55e3ad7edfed6",
          "md5": "ab141e3612bf95374650776069799310"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.4.0-javadoc.jar",
          "url": "knightlib-common-1.20.1-1.4.0-javadoc.jar",
          "size": 425550,
          "sha512": "e16c7e915ac96d774c151745372f3c0eaf96bc15612ffed57743ef75d610a12f193c9d046468206ef0c4d10c2ad81cb31dccaed6d9608f8ca0f119f497845653",
          "sha256": "40ef3473f9c80bc9c0e060c3c017b58829075e4ea5513ae833cd8eaefda4944e",
          "sha1": "5c8a9113238dcd97d3965dde327f82bb6a83206c",
          "md5": "65313149acc5ef2b822bf6c46c5a8433"
        }
      ]
    }
  ]
}
