{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-common-1.20.1",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.4.0.jar",
          "url": "knightlib-common-1.20.1-1.4.0.jar",
          "size": 179446,
          "sha512": "4f3b561ea0d8e68d53de55eb52277e62338deedb5160d76788ce2282ff915197d13b236aac5e5fa786b49df67b695df12156eefdc3d4bf711fe803d5449fcc99",
          "sha256": "237bf28f9f2d5228f71b3850329a6dabe835014d91678971d636b7574925f941",
          "sha1": "acf4533329aeb490b7bc1b14397f9c71443d9bc5",
          "md5": "6cb9cbb520a011f3db09c01ca27fba46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.4.0.jar",
          "url": "knightlib-common-1.20.1-1.4.0.jar",
          "size": 179446,
          "sha512": "4f3b561ea0d8e68d53de55eb52277e62338deedb5160d76788ce2282ff915197d13b236aac5e5fa786b49df67b695df12156eefdc3d4bf711fe803d5449fcc99",
          "sha256": "237bf28f9f2d5228f71b3850329a6dabe835014d91678971d636b7574925f941",
          "sha1": "acf4533329aeb490b7bc1b14397f9c71443d9bc5",
          "md5": "6cb9cbb520a011f3db09c01ca27fba46"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.4.0-sources.jar",
          "url": "knightlib-common-1.20.1-1.4.0-sources.jar",
          "size": 126364,
          "sha512": "bab70d55c72def9693435d7e58217b8c401978aead3c8675d8c86e548ba1a6b12240db079e19cb2150d0beecb61fca2e47ee7aa12d62bf948bf721b9c2532848",
          "sha256": "300ee53e71c4c64f7881f13b8aff9d101d7ccd9f8a4d4aadc464337ae246b885",
          "sha1": "86f34047bc57dc4e03ab8694aca55e3ad7edfed6",
          "md5": "ab141e3612bf95374650776069799310"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.4.0-javadoc.jar",
          "url": "knightlib-common-1.20.1-1.4.0-javadoc.jar",
          "size": 425550,
          "sha512": "e16c7e915ac96d774c151745372f3c0eaf96bc15612ffed57743ef75d610a12f193c9d046468206ef0c4d10c2ad81cb31dccaed6d9608f8ca0f119f497845653",
          "sha256": "40ef3473f9c80bc9c0e060c3c017b58829075e4ea5513ae833cd8eaefda4944e",
          "sha1": "5c8a9113238dcd97d3965dde327f82bb6a83206c",
          "md5": "65313149acc5ef2b822bf6c46c5a8433"
        }
      ]
    }
  ]
}
