{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-common-1.20.1",
    "version": "1.5.0q",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.5.0q.jar",
          "url": "knightlib-common-1.20.1-1.5.0q.jar",
          "size": 390490,
          "sha512": "f069861603166bc02757a0c9cfbf32b73412dc27a01149b7b371086e7f37572b646e7106c592244d7ae30454da5c703ee9a196b3747c9e9d06acf1bf000952c1",
          "sha256": "6db400828f5bbd6ae2e9227b59ffc6957133c16d38d7c970177a72e964c72519",
          "sha1": "d9e6db1bd35cde172ce1a0cadde8d42edbe920ca",
          "md5": "002e8277b1325a7fc4ca2419d8151e8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.5.0q.jar",
          "url": "knightlib-common-1.20.1-1.5.0q.jar",
          "size": 390490,
          "sha512": "f069861603166bc02757a0c9cfbf32b73412dc27a01149b7b371086e7f37572b646e7106c592244d7ae30454da5c703ee9a196b3747c9e9d06acf1bf000952c1",
          "sha256": "6db400828f5bbd6ae2e9227b59ffc6957133c16d38d7c970177a72e964c72519",
          "sha1": "d9e6db1bd35cde172ce1a0cadde8d42edbe920ca",
          "md5": "002e8277b1325a7fc4ca2419d8151e8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.5.0q-sources.jar",
          "url": "knightlib-common-1.20.1-1.5.0q-sources.jar",
          "size": 228678,
          "sha512": "a6507adb95b253ac184bb4e1319187bd1c0b1a31b9a5881b28f88e16510b9f8b688b5bc513bcdf649e02ca2903f401d3f4441e6b6e59a1a75611203b2adcf47e",
          "sha256": "6a2787e035200046e5ef88d29848c74d00e6a7a27cad0105fde512d47a3b7cbf",
          "sha1": "96884d805768c8047b8ae11ab91e3562be02e11a",
          "md5": "d8568ac988c4700caa7c92baf2a88e0b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.20.1-1.5.0q-javadoc.jar",
          "url": "knightlib-common-1.20.1-1.5.0q-javadoc.jar",
          "size": 883038,
          "sha512": "e18f312b43042152a46925b1cb993f903d9d6f1b7928e136cf16a5f6d148ab1300dc3de542125d598cae8d39d221ceacd29b2790129c571a881210926339ec95",
          "sha256": "e01be0a0ec706c9b56a714141bc5e545a2b69b0adfc3dcf9d79d882f40333f43",
          "sha1": "ab9a2d52afde16b66dc3f011877b1c620858cd61",
          "md5": "520226b3931cf45aae5ebce8b6ac8b3f"
        }
      ]
    }
  ]
}
