{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-neoforge-1.21.1",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "knightlib-neoforge-1.21.1-1.3.0.jar",
          "url": "knightlib-neoforge-1.21.1-1.3.0.jar",
          "size": 199126,
          "sha512": "30419e7574f6b53af6daacec6c4afee94e5a37893ed1a2aa19fdc700758c6ecd6132d830250201ab58399df7391cdbe79a38784109f3821b3d306f45be1125fd",
          "sha256": "156f5a3e6b2c0d39cae18d75f9a6fdfa7f675e3a568f0ba43fb96e5c0e327ea0",
          "sha1": "41b1f92e5a5828774a4126ae1a3c5f393f6fb7bf",
          "md5": "c45c0d44200ecb5195a117e7ef28f917"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-neoforge-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-neoforge-1.21.1",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.1.311"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-neoforge-1.21.1-1.3.0.jar",
          "url": "knightlib-neoforge-1.21.1-1.3.0.jar",
          "size": 199126,
          "sha512": "30419e7574f6b53af6daacec6c4afee94e5a37893ed1a2aa19fdc700758c6ecd6132d830250201ab58399df7391cdbe79a38784109f3821b3d306f45be1125fd",
          "sha256": "156f5a3e6b2c0d39cae18d75f9a6fdfa7f675e3a568f0ba43fb96e5c0e327ea0",
          "sha1": "41b1f92e5a5828774a4126ae1a3c5f393f6fb7bf",
          "md5": "c45c0d44200ecb5195a117e7ef28f917"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-neoforge-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-neoforge-1.21.1-1.3.0-sources.jar",
          "url": "knightlib-neoforge-1.21.1-1.3.0-sources.jar",
          "size": 132080,
          "sha512": "2f958c0e743f64c2f181e206aa947743c894d2ccd1124e3d0a20f99f69323407c049c128854764679ee50f021aa38c24f91115331b289a4cebaa354a0d0fa1be",
          "sha256": "9dd60c632395f513b762eab204f6e9dfd638a0aa5de97ee2e7e74c4f21324bfe",
          "sha1": "8f4ee599483515385b8550ce4428e90027d42775",
          "md5": "7c611be8a32e81bbcc523cdfac9901fd"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-neoforge-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-neoforge-1.21.1-1.3.0-javadoc.jar",
          "url": "knightlib-neoforge-1.21.1-1.3.0-javadoc.jar",
          "size": 455424,
          "sha512": "7623077a95a05d12110d509e8fbc9c402c494bf11a06ad95272cf3f55242e1a849f27cbdf0d795eb116a9fd89010ceb95c5d464e04f4d1f084019ced58aed030",
          "sha256": "8411c7f3dc916f4163cbd6c66fc0f594bcc10beb9826edf23342a80232971e78",
          "sha1": "369a5ce8666f7c8dd26940c88b81af9d6d27d05a",
          "md5": "8f8207963959df5942e87c4d778b85b4"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-neoforge-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    }
  ]
}
