{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-neoforge-1.21.1",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "knightlib-neoforge-1.21.1-1.3.0.jar",
          "url": "knightlib-neoforge-1.21.1-1.3.0.jar",
          "size": 198383,
          "sha512": "57e8b11788bc98401ab3b06b5a68aaa3341e4a1a9d674ac37c3917ddf91f0fb6f319b544f4ec024c720ab49ec59c33992630e0c5de29caa0cf7f86034cec3e20",
          "sha256": "f67f17c2db576b9326249c0134bfff33c42436cfb228060610a3f6b9a3038df2",
          "sha1": "6c011a2602f008d7ebc5c7f85181a7e39d184a25",
          "md5": "b36fc68c8940f44ee1112bd087235e6d"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-neoforge-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-neoforge-1.21.1",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.1.311"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-neoforge-1.21.1-1.3.0.jar",
          "url": "knightlib-neoforge-1.21.1-1.3.0.jar",
          "size": 198383,
          "sha512": "57e8b11788bc98401ab3b06b5a68aaa3341e4a1a9d674ac37c3917ddf91f0fb6f319b544f4ec024c720ab49ec59c33992630e0c5de29caa0cf7f86034cec3e20",
          "sha256": "f67f17c2db576b9326249c0134bfff33c42436cfb228060610a3f6b9a3038df2",
          "sha1": "6c011a2602f008d7ebc5c7f85181a7e39d184a25",
          "md5": "b36fc68c8940f44ee1112bd087235e6d"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-neoforge-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-neoforge-1.21.1-1.3.0-sources.jar",
          "url": "knightlib-neoforge-1.21.1-1.3.0-sources.jar",
          "size": 131434,
          "sha512": "abb3e93bd7844d0c8565fd7b1a793379a680390c3aec5d7e6fdc4eb8ddec8eaae3f3bc38c5306cf9667c6ee8a685ea0acf54ebc05be1698fd4e96cbe2a40d7b6",
          "sha256": "17ce5adb3eadfe4e6e75b716fe59e17132a1c020889d0eac7147f020155fc2f4",
          "sha1": "a9414aa186d60e8017f8ab23b3f83ab72acbd370",
          "md5": "52d3eeba6d3b8e0b6c69b91209bb47bc"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-neoforge-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-neoforge-1.21.1-1.3.0-javadoc.jar",
          "url": "knightlib-neoforge-1.21.1-1.3.0-javadoc.jar",
          "size": 453411,
          "sha512": "a00f5fc054333b0251b1d767991a0e818dad0addfc59c164872c158868989e1d66464bf24dc8fb039654fb620061aaa28af28f233a95364865dee6610a0ba253",
          "sha256": "d34cb46c2f100c39582c3205de68c105f16f3a1b3b26654ce561e7c305466411",
          "sha1": "f5c8dd90304d603790276e69674989498a9793b1",
          "md5": "d1576f492ccb2980e8bd0ed8591e99f2"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-neoforge-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    }
  ]
}
