{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-neoforge-1.21.1",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "knightlib-neoforge-1.21.1-1.3.0.jar",
          "url": "knightlib-neoforge-1.21.1-1.3.0.jar",
          "size": 198394,
          "sha512": "91b34485f8e5bc780ffa11077b50a8308a9b1af8bb94f1e734418d36b93210719cc369e21991d3b2157a62be2c40556135b6a594434c41f87237d6ba4c7c33ff",
          "sha256": "50eeac4e6dcbb9602cbdc57ce201a9eb14e12dc0636ba0eae9ff6975c302a031",
          "sha1": "5174e944e36d2020019f449dc17dd47376d3e14e",
          "md5": "2b6952491125a7df41b2642ca1e88352"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-neoforge-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-neoforge-1.21.1",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.1.311"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-neoforge-1.21.1-1.3.0.jar",
          "url": "knightlib-neoforge-1.21.1-1.3.0.jar",
          "size": 198394,
          "sha512": "91b34485f8e5bc780ffa11077b50a8308a9b1af8bb94f1e734418d36b93210719cc369e21991d3b2157a62be2c40556135b6a594434c41f87237d6ba4c7c33ff",
          "sha256": "50eeac4e6dcbb9602cbdc57ce201a9eb14e12dc0636ba0eae9ff6975c302a031",
          "sha1": "5174e944e36d2020019f449dc17dd47376d3e14e",
          "md5": "2b6952491125a7df41b2642ca1e88352"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-neoforge-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-neoforge-1.21.1-1.3.0-sources.jar",
          "url": "knightlib-neoforge-1.21.1-1.3.0-sources.jar",
          "size": 131485,
          "sha512": "34b1b6f437231672b734badd11a1c95ffba2a5e705e66437c855ce916593415f6d5254d6dc14450956578697884dc0ecf9775264e3f07266269d2245aa8eb056",
          "sha256": "7b546c9e59cdeef06295f4a6308e639611ba84b75c9a8b2559920d4fcf77bea8",
          "sha1": "2d6d50a0268a702eedc28b3cb29a3b6b4fb0e66f",
          "md5": "fdea4f6a7551be3bff191aec6b963494"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-neoforge-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-neoforge-1.21.1-1.3.0-javadoc.jar",
          "url": "knightlib-neoforge-1.21.1-1.3.0-javadoc.jar",
          "size": 453411,
          "sha512": "a00f5fc054333b0251b1d767991a0e818dad0addfc59c164872c158868989e1d66464bf24dc8fb039654fb620061aaa28af28f233a95364865dee6610a0ba253",
          "sha256": "d34cb46c2f100c39582c3205de68c105f16f3a1b3b26654ce561e7c305466411",
          "sha1": "f5c8dd90304d603790276e69674989498a9793b1",
          "md5": "d1576f492ccb2980e8bd0ed8591e99f2"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-neoforge-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    }
  ]
}
