{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.tooltipoverhaul",
    "module": "tooltipoverhaul-fabric-1.20.1",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "tooltipoverhaul-fabric-1.20.1-1.5.0.jar",
          "url": "tooltipoverhaul-fabric-1.20.1-1.5.0.jar",
          "size": 807328,
          "sha512": "5a0f0ace9e6ec097b949d709ad07d1fc901dd21ad7898d27598171c1a0970f02524d2c2ebb85ccae9be882e48c99f5ab789041079f291fc8ae0a7adfe812843d",
          "sha256": "3ad128acf92ce79710ed0020c6a522373ffb0bbcfe282457c3492bf47bf4270b",
          "sha1": "a01bf09aa6972db31b9fb8f87aa13fdd3770f042",
          "md5": "01d2ed415c3e7c4089ab44132524085a"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-fabric-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.5.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "fabric",
          "version": "1.5.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "module": "tooltipoverhaul-common-1.20.1",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.8+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "tooltipoverhaul-fabric-1.20.1-1.5.0.jar",
          "url": "tooltipoverhaul-fabric-1.20.1-1.5.0.jar",
          "size": 807328,
          "sha512": "5a0f0ace9e6ec097b949d709ad07d1fc901dd21ad7898d27598171c1a0970f02524d2c2ebb85ccae9be882e48c99f5ab789041079f291fc8ae0a7adfe812843d",
          "sha256": "3ad128acf92ce79710ed0020c6a522373ffb0bbcfe282457c3492bf47bf4270b",
          "sha1": "a01bf09aa6972db31b9fb8f87aa13fdd3770f042",
          "md5": "01d2ed415c3e7c4089ab44132524085a"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-fabric-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.5.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "fabric",
          "version": "1.5.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-fabric-1.20.1-1.5.0-sources.jar",
          "url": "tooltipoverhaul-fabric-1.20.1-1.5.0-sources.jar",
          "size": 370233,
          "sha512": "0fe0f826e1f51d2a0734eb4e8dca5580d4f54e93548006e93af10dda88a3219577cd4b59c85bd0f05f364288368b543fa7a95342e14713a8cf14c5df19810ccb",
          "sha256": "c0a3416f08d587b1792db25ee9bdfc154d2e7e599a3d849e04e4b3a14875fa52",
          "sha1": "c6dc5557644cecaff172f1aa44439af4283938bf",
          "md5": "b98dd2204e517b8c6df1c2d8c1c6b126"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-fabric-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.5.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "fabric",
          "version": "1.5.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-fabric-1.20.1-1.5.0-javadoc.jar",
          "url": "tooltipoverhaul-fabric-1.20.1-1.5.0-javadoc.jar",
          "size": 593736,
          "sha512": "79a02b4ea6bdba1e683f8959e001ba1e280e0252fa869ac651f4c33f31e0117c31dfe097d106b7e6e34bed40b2c3522788d62982554771d809ac08ed0a3ebce1",
          "sha256": "2575b069fd65ca2d342478399cf9d7a866fd390b1e792b6921a51ca0d60d74a5",
          "sha1": "58dca711def3d743d769278584b46f7338ee128a",
          "md5": "58f86f86023907730a48857d6dc1764f"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-fabric-1.20.1",
          "version": "1.5.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.5.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "fabric",
          "version": "1.5.0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "tooltipoverhaul-fabric-1.20.1-1.5.0-dev-shadow.jar",
          "url": "tooltipoverhaul-fabric-1.20.1-1.5.0-dev-shadow.jar",
          "size": 792719,
          "sha512": "3ded6e8c6015ca5fcab2aa529b1e6724a1c3bdf164d61a8b0e31fba78e108bbd0306e772df48aef1643f6409a2279b25c92e94a9d9cf3a6c6e9d262af203413f",
          "sha256": "b5e7b98b8013d846ff75e3b9630afcc8c29d50ad4313d851ac9106795240b38d",
          "sha1": "4c3183f58f2de2b4c835dad8e7f40cc93fe0e43f",
          "md5": "0650a00727ae636f8903a0e2c59f0fab"
        }
      ]
    }
  ]
}
