{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-fabric-1.20.1",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.3.0.jar",
          "url": "knightlib-fabric-1.20.1-1.3.0.jar",
          "size": 396841,
          "sha512": "4f2ac7b04ebe0de65180f86bdcc96ac44e22a69fe5de6326fa19ac51e8da358de638b1f9464bbb79d862f4714d882e68dc99739f6a7f162573a5683646305ad4",
          "sha256": "00fe7af8e725e661279bf5d65fc55052cae3c50744b4b89f004c2bfb0ab6d298",
          "sha1": "ac906d4adf76e7766673e1eea379a6cf5ae2b664",
          "md5": "7e9c0a0b05e6ca3a2174df489fc2b540"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.xylonity.knightlib",
          "module": "knightlib-common-1.20.1",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-fabric-1.20.1",
          "version": {
            "requires": "4.7.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.3.0.jar",
          "url": "knightlib-fabric-1.20.1-1.3.0.jar",
          "size": 396841,
          "sha512": "4f2ac7b04ebe0de65180f86bdcc96ac44e22a69fe5de6326fa19ac51e8da358de638b1f9464bbb79d862f4714d882e68dc99739f6a7f162573a5683646305ad4",
          "sha256": "00fe7af8e725e661279bf5d65fc55052cae3c50744b4b89f004c2bfb0ab6d298",
          "sha1": "ac906d4adf76e7766673e1eea379a6cf5ae2b664",
          "md5": "7e9c0a0b05e6ca3a2174df489fc2b540"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.3.0-sources.jar",
          "url": "knightlib-fabric-1.20.1-1.3.0-sources.jar",
          "size": 129905,
          "sha512": "b6dd3c13bd5a648a683d2b06e8bd74c2f8c29cd3d1ca8229e44d433d1654f02c10b80cbd4d2a64698ae9344b0aa9bc318f9e31cd0f274153e0014027106bc191",
          "sha256": "0dadf801ee3b112ac0055504b5a75848da4144f0c0719625b9fb4eb9c1e7e7dd",
          "sha1": "8cb19eaaaf3ba02311a15e4d41668276a2bc0013",
          "md5": "89dc85adf1f26a5adc941f6349bbca0c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.3.0-javadoc.jar",
          "url": "knightlib-fabric-1.20.1-1.3.0-javadoc.jar",
          "size": 356741,
          "sha512": "623ee772b67259bbaa0202a226b90b4810251c8875177ab3254c1c3fd131d4dcc1c3180a32ee0cfdd9955ab31a4630ecad93f2f7394d6785a4faaacbf853004d",
          "sha256": "91ccef2de3635e458cc3096cab8b6bf5661590584915b61b5acb426e466450e3",
          "sha1": "e5f6b3026a0f6f21c37381a88b460d0403037bca",
          "md5": "ddeeda4dc7bfd59056a6c1b1162aae94"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.3.0-dev-shadow.jar",
          "url": "knightlib-fabric-1.20.1-1.3.0-dev-shadow.jar",
          "size": 385673,
          "sha512": "ada79f68aa643110814dd94bd228a831d9673ce47b7fe1a69f61130b0d5b1c69e73f000c7e6055a2ceea38200a5278dcae0c3db31a9527a1cccf97139628408f",
          "sha256": "3dc74a204966ceee434725aba307ae994799eb5b8bd4eef283a28fbb1c8d8974",
          "sha1": "bad06c00553233aae49a78268aa9e1cde90000bc",
          "md5": "741a45040b422b8a1f267a7bae84f0e3"
        }
      ]
    }
  ]
}
