{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-fabric-1.20.1",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.3.0.jar",
          "url": "knightlib-fabric-1.20.1-1.3.0.jar",
          "size": 417162,
          "sha512": "c06a80ff1cfcf03fa18dc382ee2c117c10b5d61e10d5fc8fb067904cce05a5a6db81bdcc9ef288c961e49d00cad248f7dd360307dcb2d34f279fa09ce7fc2a5b",
          "sha256": "9822dbea7848fb2b99e64e204f2db8f0ccedef2fa097088b979c4b4a814ce3f1",
          "sha1": "5b7140d8bc8a8f24829ce9813608ccbd5791e303",
          "md5": "5a103cbd49b6913dae8cab80223c5970"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.xylonity.knightlib",
          "module": "knightlib-common-1.20.1",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-fabric-1.20.1",
          "version": {
            "requires": "4.7.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.3.0.jar",
          "url": "knightlib-fabric-1.20.1-1.3.0.jar",
          "size": 417162,
          "sha512": "c06a80ff1cfcf03fa18dc382ee2c117c10b5d61e10d5fc8fb067904cce05a5a6db81bdcc9ef288c961e49d00cad248f7dd360307dcb2d34f279fa09ce7fc2a5b",
          "sha256": "9822dbea7848fb2b99e64e204f2db8f0ccedef2fa097088b979c4b4a814ce3f1",
          "sha1": "5b7140d8bc8a8f24829ce9813608ccbd5791e303",
          "md5": "5a103cbd49b6913dae8cab80223c5970"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.3.0-sources.jar",
          "url": "knightlib-fabric-1.20.1-1.3.0-sources.jar",
          "size": 141490,
          "sha512": "01ff5bdad1053429b5631a25a128a91e6e184407208bb652ef921afda0a4974e3799f736acb0d6376e881093292d03ccc73cc3844447654e86f5e6b0e7b31fe5",
          "sha256": "e0834ee9a46d7032bc51bc6f25fa9d34d5f0a607edbf5061fa11b1f6a018fa6e",
          "sha1": "83ecdacc0d2da1231459043c616ffcfddc9720bb",
          "md5": "e23721db4875130060fcee6df8764304"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.3.0-javadoc.jar",
          "url": "knightlib-fabric-1.20.1-1.3.0-javadoc.jar",
          "size": 408751,
          "sha512": "ee75574d89b93e671ab79312a6b5306c86dd110883ac22d5e1ef28e7176310b44976538d2bc5e89744c5604a3ea771a49955636a4efb0df9a8480ccc26ed24df",
          "sha256": "c93d29a97896abac80b104e725e2276039038b506c63789f000adc57bf889314",
          "sha1": "639cfd6b485a44f3e62aad662c33d50cabb6eb1c",
          "md5": "598c18aa852fcc08d7849a8646647fec"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.3.0-dev-shadow.jar",
          "url": "knightlib-fabric-1.20.1-1.3.0-dev-shadow.jar",
          "size": 405759,
          "sha512": "3af31707c93255a4ea1e6d8e6a9208e007fd78c8804e6da443d4b4abc8121b9d481106caa61618d788ae49e78d56ad13ec0fdfe55f2d13bd9990342e9cbb8925",
          "sha256": "3a91521afb0abcc94476e9b6fcd2c6d7f9072b8d3b4567ff946af932a7b7f877",
          "sha1": "cd13e9a7a1e077099a30d956f376fadd9611d6a9",
          "md5": "5f729ee213bad5716c6d14aefa7ab6b4"
        }
      ]
    }
  ]
}
