{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-fabric-1.20.1",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.3.0.jar",
          "url": "knightlib-fabric-1.20.1-1.3.0.jar",
          "size": 399964,
          "sha512": "df16c5859446fcd44a118f9fafa1b4e52ef44523b5dcce1f9e7b8b065fef1b64690abb7792f915507ad3cf3d822b4f88beb2fd4c1d8c09dfcaf20b05146ef692",
          "sha256": "e7a2cc0f7a61ad777d1e7d65266f028310f20b4f106984119daf1858b3ce4f14",
          "sha1": "81ddb241862308f58099d8e9ff5de39cb605b3d6",
          "md5": "0493afcf82d20789a41f9af2aadaa419"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.xylonity.knightlib",
          "module": "knightlib-common-1.20.1",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-fabric-1.20.1",
          "version": {
            "requires": "4.7.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.3.0.jar",
          "url": "knightlib-fabric-1.20.1-1.3.0.jar",
          "size": 399964,
          "sha512": "df16c5859446fcd44a118f9fafa1b4e52ef44523b5dcce1f9e7b8b065fef1b64690abb7792f915507ad3cf3d822b4f88beb2fd4c1d8c09dfcaf20b05146ef692",
          "sha256": "e7a2cc0f7a61ad777d1e7d65266f028310f20b4f106984119daf1858b3ce4f14",
          "sha1": "81ddb241862308f58099d8e9ff5de39cb605b3d6",
          "md5": "0493afcf82d20789a41f9af2aadaa419"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.3.0-sources.jar",
          "url": "knightlib-fabric-1.20.1-1.3.0-sources.jar",
          "size": 132588,
          "sha512": "842ded1c6307624d4f43355936891371526f7404e8702f70650387f73f3a06eff687a15cf81c14d55975d39d87b014689c6c55fd2b3652238c072531b35003d6",
          "sha256": "71a2164f043f47d936bc70a9355cac64143250f75b625bdc766593b0f20bc9d1",
          "sha1": "91992126d5020b66e5adc28d30a71fb36f2efcc7",
          "md5": "5c73532f8aec8decd53db1987a3e6dd2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.3.0-javadoc.jar",
          "url": "knightlib-fabric-1.20.1-1.3.0-javadoc.jar",
          "size": 356741,
          "sha512": "623ee772b67259bbaa0202a226b90b4810251c8875177ab3254c1c3fd131d4dcc1c3180a32ee0cfdd9955ab31a4630ecad93f2f7394d6785a4faaacbf853004d",
          "sha256": "91ccef2de3635e458cc3096cab8b6bf5661590584915b61b5acb426e466450e3",
          "sha1": "e5f6b3026a0f6f21c37381a88b460d0403037bca",
          "md5": "ddeeda4dc7bfd59056a6c1b1162aae94"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.3.0-dev-shadow.jar",
          "url": "knightlib-fabric-1.20.1-1.3.0-dev-shadow.jar",
          "size": 388783,
          "sha512": "d0e04d6f487907b8adfc6b52d1fbbaeb6ed57c0001c111bfb7c8093673585ef2591a18f54f6ce6ad01b1b14551828821b0ae5c3698a70d4203583cf47917ada6",
          "sha256": "a59634b4b48e781f32db9c9ca0453a69f2d3439746c666877b60efa3f493725c",
          "sha1": "ae89baebe4b5a08852a5c0010b85d44f273709d9",
          "md5": "16ef5322bf05cb72a52cbf8f95ac3838"
        }
      ]
    }
  ]
}
