{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.tooltipsoverhaul",
    "module": "tooltipoverhaul-fabric-1.20.1",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "tooltipoverhaul-fabric-1.20.1-1.0.0.jar",
          "url": "tooltipoverhaul-fabric-1.20.1-1.0.0.jar",
          "size": 494318,
          "sha512": "8ee2f54766600fcb2c3a6d178f5025eb9ef6e1856bd06f5a50d1d5e2742b63a139347c2655eac2bab51ccf475a17d97cf8cb9ae3545bbe2dda88106dd1c17019",
          "sha256": "dfbb02d00dfe4853f7e78f28898592409c72f605c6d18bf064bfc39d9d3d6642",
          "sha1": "b21341630afe430c84e47d45b0210cfdf4ad565d",
          "md5": "c5952c685735c026a2bcbde83c5a2c65"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipsoverhaul",
          "name": "tooltipoverhaul-fabric-1.20.1",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipsoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipsoverhaul",
          "name": "fabric",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.xylonity.tooltipsoverhaul",
          "module": "tooltipoverhaul-common-1.20.1",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "tooltipoverhaul-fabric-1.20.1-1.0.0.jar",
          "url": "tooltipoverhaul-fabric-1.20.1-1.0.0.jar",
          "size": 494318,
          "sha512": "8ee2f54766600fcb2c3a6d178f5025eb9ef6e1856bd06f5a50d1d5e2742b63a139347c2655eac2bab51ccf475a17d97cf8cb9ae3545bbe2dda88106dd1c17019",
          "sha256": "dfbb02d00dfe4853f7e78f28898592409c72f605c6d18bf064bfc39d9d3d6642",
          "sha1": "b21341630afe430c84e47d45b0210cfdf4ad565d",
          "md5": "c5952c685735c026a2bcbde83c5a2c65"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipsoverhaul",
          "name": "tooltipoverhaul-fabric-1.20.1",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipsoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipsoverhaul",
          "name": "fabric",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-fabric-1.20.1-1.0.0-sources.jar",
          "url": "tooltipoverhaul-fabric-1.20.1-1.0.0-sources.jar",
          "size": 195462,
          "sha512": "7e01fe6107fffa5247acc35c91a26831e0b358e9d2a1c6b32bd4908ee5934f46e600a49880a147374f38ebaaafab648ccadd4544b52a512baf76fb5b3ae5859b",
          "sha256": "96265c0fe362d760f182fc3fc97a7fd6d8e091c1a68174caea61a59fce48ebb3",
          "sha1": "8d6f99f5fdda0f5159b968b9705dffa20f3f6f6b",
          "md5": "7a2e99b8f8605bfd46b983b93138a18b"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipsoverhaul",
          "name": "tooltipoverhaul-fabric-1.20.1",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipsoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipsoverhaul",
          "name": "fabric",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-fabric-1.20.1-1.0.0-javadoc.jar",
          "url": "tooltipoverhaul-fabric-1.20.1-1.0.0-javadoc.jar",
          "size": 376777,
          "sha512": "a9109d17a24b242bcd3b4fb1bfe6baf3c9b0d98960f86669aa8a42add988963e987372e281224888f0c7752601acc9d9475249c9237b1ee6c23663b60bc6f4d1",
          "sha256": "e37fd6e49eb768842194115bd30c07cab7ff8eae90f2f094d49260eb7a304537",
          "sha1": "9822720af54c094dc4b11d77ce2f4247084300d5",
          "md5": "16ce07b2986003f8147052999f8187b5"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipsoverhaul",
          "name": "tooltipoverhaul-fabric-1.20.1",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipsoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipsoverhaul",
          "name": "fabric",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "tooltipoverhaul-fabric-1.20.1-1.0.0-dev-shadow.jar",
          "url": "tooltipoverhaul-fabric-1.20.1-1.0.0-dev-shadow.jar",
          "size": 482609,
          "sha512": "ba473830ae6bda06efd5664b5ae35c8ae8f0b15d670850b0bef7fdd3dfd521ae980671be6da223417c838862e4978b0c0fe7c8075f48bc3c3a15607b86d83b3c",
          "sha256": "b9ea708952b0b3060eecd695c56166274cddafccaff94c2a573e68bae1294f47",
          "sha1": "968c6b212a491b86ff04430a90e6c261cabd13da",
          "md5": "500485fff4e44f31ca09d8bbdc4bd13e"
        }
      ]
    }
  ]
}
