{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.tooltipoverhaul",
    "module": "tooltipoverhaul-fabric-1.20.1",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "tooltipoverhaul-fabric-1.20.1-1.0.0.jar",
          "url": "tooltipoverhaul-fabric-1.20.1-1.0.0.jar",
          "size": 494316,
          "sha512": "e85302bf7719b0d805210212d2b73622bc31b8a753ca4a140b4a0f9946b07044480c1206d2490a19e643a6dec1a197ba51cb8f969a1e325344c33270b32b81ca",
          "sha256": "6f288d3cc8760e3187c7c1b4af6269367c3d13644312bfc9fea2159dab45881d",
          "sha1": "65611f6e09c9b3100464f179f7e424eb221e6577",
          "md5": "c1f79da7aceaa61fb9400f716757e48c"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-fabric-1.20.1",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "fabric",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "module": "tooltipoverhaul-common-1.20.1",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "tooltipoverhaul-fabric-1.20.1-1.0.0.jar",
          "url": "tooltipoverhaul-fabric-1.20.1-1.0.0.jar",
          "size": 494316,
          "sha512": "e85302bf7719b0d805210212d2b73622bc31b8a753ca4a140b4a0f9946b07044480c1206d2490a19e643a6dec1a197ba51cb8f969a1e325344c33270b32b81ca",
          "sha256": "6f288d3cc8760e3187c7c1b4af6269367c3d13644312bfc9fea2159dab45881d",
          "sha1": "65611f6e09c9b3100464f179f7e424eb221e6577",
          "md5": "c1f79da7aceaa61fb9400f716757e48c"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-fabric-1.20.1",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "fabric",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-fabric-1.20.1-1.0.0-sources.jar",
          "url": "tooltipoverhaul-fabric-1.20.1-1.0.0-sources.jar",
          "size": 195460,
          "sha512": "fe4eee2705e6a4413bb771f6e62c8b30be477d8140897c82e368690fec4c650e4b2715388a59e7d48764d0edd08897f0acd7824391a2555914f544e224f975d0",
          "sha256": "1c56ab03df185dbae040637b6c123f6463985b8ee4603c6e2cc84aacea93fbd9",
          "sha1": "14c00e2be0d4ace1570bd0fc3ae5c85c15fa5bb4",
          "md5": "38153f715df4204b45e32d6ae6c73ba9"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-fabric-1.20.1",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "fabric",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-fabric-1.20.1-1.0.0-javadoc.jar",
          "url": "tooltipoverhaul-fabric-1.20.1-1.0.0-javadoc.jar",
          "size": 376777,
          "sha512": "2d7ea0af9c56f282189b04b6722b835d245fda3b477b97e3e546b928780126233d50d654569f6bf2776cff4634c47c50bd8a282716579fef4bad1230a4fb9a12",
          "sha256": "d1828ac04c5dcb4aa8615702b65d6e1dc1cc0987122e49eedbb5e5c0505b0c14",
          "sha1": "584c4c4e1451a05c609db945dc16609b18f699e6",
          "md5": "c9ec4cd7551c2c587892f6cf0cb43225"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-fabric-1.20.1",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "fabric",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "tooltipoverhaul-fabric-1.20.1-1.0.0-dev-shadow.jar",
          "url": "tooltipoverhaul-fabric-1.20.1-1.0.0-dev-shadow.jar",
          "size": 482607,
          "sha512": "b4bd5a4a6cc1b80e4d80a2658ce9d42f8f0c44223c6d7a22ebcd4a63e9be55768e5f1fae6238bfe58fffe12c703ef93b2826c66e130da3f218de41e34d5343da",
          "sha256": "add1d75e62cc9c6bfef653240f63d831b32a2f9b7dd65b97f7554f01c997cf8f",
          "sha1": "b616d15f022264ff1a60d577e0de81bfc0e4cc61",
          "md5": "9894653b422b2eb3e2b7c5e602dd3727"
        }
      ]
    }
  ]
}
