{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-fabric-1.20.1",
    "version": "1.5.0w",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.5.0w.jar",
          "url": "knightlib-fabric-1.20.1-1.5.0w.jar",
          "size": 751063,
          "sha512": "a3de3317c9f530bfe57c4465ed0c04c29e82bacef8a56e81cfa69c86a3e05f4d2110f6bba591881110be4b70fa5a73cffab5df40a726045592d577456427bf39",
          "sha256": "623fb763ba4c63dd00a9e07ab8dd7de08024505ce622172eec346d8262ffa89f",
          "sha1": "5c61ec849ae013a1fe546cae48cc932e16724c1c",
          "md5": "1a53593a4329cd574b63c340afa1336d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.xylonity.knightlib",
          "module": "knightlib-common-1.20.1",
          "version": {
            "requires": "1.5.0w"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-fabric-1.20.1",
          "version": {
            "requires": "4.7.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.5.0w.jar",
          "url": "knightlib-fabric-1.20.1-1.5.0w.jar",
          "size": 751063,
          "sha512": "a3de3317c9f530bfe57c4465ed0c04c29e82bacef8a56e81cfa69c86a3e05f4d2110f6bba591881110be4b70fa5a73cffab5df40a726045592d577456427bf39",
          "sha256": "623fb763ba4c63dd00a9e07ab8dd7de08024505ce622172eec346d8262ffa89f",
          "sha1": "5c61ec849ae013a1fe546cae48cc932e16724c1c",
          "md5": "1a53593a4329cd574b63c340afa1336d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.5.0w-sources.jar",
          "url": "knightlib-fabric-1.20.1-1.5.0w-sources.jar",
          "size": 323371,
          "sha512": "5a7a7a2b5780de13aa383822e2cb536aa0f69b8b790c26427aaaf66e30739b0866f614be690b5dc23a995c5a8527af0322d8ddf203b8280b8112a5ef4c2f3910",
          "sha256": "1bc07138da1a35b368fa690a2e231f5da53140b1b704d70b6027dec2868327fa",
          "sha1": "9186de5f8cba5a4d5f986441786bb85e65bd672b",
          "md5": "51d789e9c8f6eb6fbf6e55f1500f3b5f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.5.0w-javadoc.jar",
          "url": "knightlib-fabric-1.20.1-1.5.0w-javadoc.jar",
          "size": 1168334,
          "sha512": "950fd47231bc1ff6318c570ea3b91058554b7a1940b44037cbeef5b5d8a323a0ba27b3216adcc04e00f503f0e026108ba0bb954fbd4aad357b565fb88a325108",
          "sha256": "1abd684b6bfce3a232b2a86a06735b1c39d2445ff8500dde4222bdcea3d9efcc",
          "sha1": "aa85846f252f2fedd33df7815e93de6d221e8455",
          "md5": "5a3560c14959dbfe3e949ade5395b32f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.5.0w-dev-shadow.jar",
          "url": "knightlib-fabric-1.20.1-1.5.0w-dev-shadow.jar",
          "size": 731121,
          "sha512": "55ffdfc2c49411d7e6d2db4b0ec5f93f01d1984dc11ec60da47b0bbc70792e01f67fba577d3a1c7a7e057ebf729b674485cd281b33085a745fef66c2bc721260",
          "sha256": "d3e14a7ea53cb75070de1d371eaaff7053e2297e646eed78d3d91accbdd7b868",
          "sha1": "d91d6a92e905e9dd78c80150dc314b4892951cdc",
          "md5": "0a95413f4e5a0f08233eaa7281c997bc"
        }
      ]
    }
  ]
}
