{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-common-1.21.1",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "knightlib-common-1.21.1-1.3.0.jar",
          "url": "knightlib-common-1.21.1-1.3.0.jar",
          "size": 106041,
          "sha512": "94ea3613302709105bac694c93853db1916c50aa2ff5530d02e5a612ed83179732abaa9b0d4590dab97ab539579e36c34a9b1f9d5975cccd8c3681fe6edf0310",
          "sha256": "8038a145ba8ba239f66678b74c1d0acc3ec83dc841e3666a9a2051494d683821",
          "sha1": "9a6605c6248db4be9fbbe7af94ec4ee7d920785e",
          "md5": "a50e001a129ccf7c4fd6084ed05a5f08"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-common-1.21.1",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.21.1-1.3.0.jar",
          "url": "knightlib-common-1.21.1-1.3.0.jar",
          "size": 106041,
          "sha512": "94ea3613302709105bac694c93853db1916c50aa2ff5530d02e5a612ed83179732abaa9b0d4590dab97ab539579e36c34a9b1f9d5975cccd8c3681fe6edf0310",
          "sha256": "8038a145ba8ba239f66678b74c1d0acc3ec83dc841e3666a9a2051494d683821",
          "sha1": "9a6605c6248db4be9fbbe7af94ec4ee7d920785e",
          "md5": "a50e001a129ccf7c4fd6084ed05a5f08"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-common-1.21.1",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.21.1-1.3.0-sources.jar",
          "url": "knightlib-common-1.21.1-1.3.0-sources.jar",
          "size": 86659,
          "sha512": "5c310ad243db1988ac13a1bf78fdc43fd6f3286f8cdba448afbbc4651fbb9639ca74237f845e510b380d52ce8015aab051f2a7524334af4c399854778c30aafe",
          "sha256": "6cbde5370459163ffc9fb78858f14faaef60e0094e360373c3d00fc07f180f03",
          "sha1": "9a402a09773da8c461134231a25082304cf9c5f0",
          "md5": "3b343b2dc0f22a9c28759fe45bad35e5"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-common-1.21.1",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.21.1-1.3.0-javadoc.jar",
          "url": "knightlib-common-1.21.1-1.3.0-javadoc.jar",
          "size": 228799,
          "sha512": "b167d2e74289e01b50ce49c3245d17af2606c207d72486033c6f3720953490227366806c76b14eb25451321b037219f5c9c63af95352631450af62f259f4aebb",
          "sha256": "0c0c81c8350ded9d160b439a6ce9d49588a913c8b277ba42fc829c12f526cdc5",
          "sha1": "a86a93f7dbacc65c96e25485488cc2cf6ef22071",
          "md5": "fb4a8d734ddb5015bd0eb592118dd6f8"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-common-1.21.1",
          "version": "1.3.0"
        }
      ]
    }
  ]
}
