{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-common-1.21.1",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "knightlib-common-1.21.1-1.3.0.jar",
          "url": "knightlib-common-1.21.1-1.3.0.jar",
          "size": 105911,
          "sha512": "c23e1b71e44311c93bd188c35b178421ab24b1cc4d9de3a8343a6f236f4b1e916435e47fd0cd8ee503c56b331374cc52632da35506a53603fe65cca7132f2d1b",
          "sha256": "4ce2f966394ec9984c9537c9eb3c0ac3439b494c8fb985289ce10ddfc405d435",
          "sha1": "5256fdd7dee04328c3f7daa681a52894690543d7",
          "md5": "2cdea3237b873d023e43147f15b5b079"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-common-1.21.1",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.21.1-1.3.0.jar",
          "url": "knightlib-common-1.21.1-1.3.0.jar",
          "size": 105911,
          "sha512": "c23e1b71e44311c93bd188c35b178421ab24b1cc4d9de3a8343a6f236f4b1e916435e47fd0cd8ee503c56b331374cc52632da35506a53603fe65cca7132f2d1b",
          "sha256": "4ce2f966394ec9984c9537c9eb3c0ac3439b494c8fb985289ce10ddfc405d435",
          "sha1": "5256fdd7dee04328c3f7daa681a52894690543d7",
          "md5": "2cdea3237b873d023e43147f15b5b079"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-common-1.21.1",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.21.1-1.3.0-sources.jar",
          "url": "knightlib-common-1.21.1-1.3.0-sources.jar",
          "size": 86457,
          "sha512": "c7000d99f539c17e16805cae2ac67ad6eeb95d0608e43ea2e326a50b0474af77da0697f2aa59a274880e33ae4df6680a10e54ab6b53c998656b22b001f8bd0f9",
          "sha256": "00a5d5deed68f4562d3cf2da3e94766361805201ce4479b72c7a8dc9ef69fd07",
          "sha1": "350eb97a7a719ec5268f823aa4a3a2cc5cdf0c02",
          "md5": "8ed3d7b1b17eb778a4fcfde61e4ae527"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-common-1.21.1",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.21.1-1.3.0-javadoc.jar",
          "url": "knightlib-common-1.21.1-1.3.0-javadoc.jar",
          "size": 228793,
          "sha512": "53e2ff064465eb162269793a76f39225c07dea65ff1b95fa010175c4caeeebd6a37851049968266a3471dda126f29de64dea5eb869ce67b7aa955e200816bd3b",
          "sha256": "a8253a0f25ccab06ca57d258dac2021fa7a84f8238ab3e05d45ffae8dc072fdd",
          "sha1": "0dcf8f755a6eb0de8fc670a2dd7b05ab93601fa4",
          "md5": "1f35837644f35ad9d3d984ac0736ec52"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-common-1.21.1",
          "version": "1.3.0"
        }
      ]
    }
  ]
}
