{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-fabric-1.21.1",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.21.1-1.3.0.jar",
          "url": "knightlib-fabric-1.21.1-1.3.0.jar",
          "size": 420131,
          "sha512": "4e41478b12606f50291e640e73a25cd1bd866a05ff67e42f9a28b045aaeb72ac3baff0fddd1818951baf9815422cb418814af7714a84db5ecb1a823176776b6d",
          "sha256": "7138cd34bf104994d1d735a6d13b538223cf988e0fe677a9b11d679a9dc09c24",
          "sha1": "949a268e7b4f475486d191e1b51245c4bf0490fd",
          "md5": "0e6cf794964921dbbde1831198af2074"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-fabric-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-fabric-1.21.1",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.21.1.311"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.109.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.21.1-1.3.0.jar",
          "url": "knightlib-fabric-1.21.1-1.3.0.jar",
          "size": 420131,
          "sha512": "4e41478b12606f50291e640e73a25cd1bd866a05ff67e42f9a28b045aaeb72ac3baff0fddd1818951baf9815422cb418814af7714a84db5ecb1a823176776b6d",
          "sha256": "7138cd34bf104994d1d735a6d13b538223cf988e0fe677a9b11d679a9dc09c24",
          "sha1": "949a268e7b4f475486d191e1b51245c4bf0490fd",
          "md5": "0e6cf794964921dbbde1831198af2074"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-fabric-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.21.1-1.3.0-sources.jar",
          "url": "knightlib-fabric-1.21.1-1.3.0-sources.jar",
          "size": 142606,
          "sha512": "1a05e4deae3916c690be4f6fbb3230178d778b29d21a6a920cdc67ea948700449a772c434e74620e0aa195a4965bf5b23d20f4c37fe925055050e5087264424f",
          "sha256": "d8b9b646ef21f95d59846cdc5c93be54a521ad9ef731e516f0ab306ef1165190",
          "sha1": "5582a9881c715c28bbbc75fc7f02dedd1b38155d",
          "md5": "7090ad79e89a0bda5b8a6258474f5ec7"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-fabric-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.21.1-1.3.0-javadoc.jar",
          "url": "knightlib-fabric-1.21.1-1.3.0-javadoc.jar",
          "size": 435934,
          "sha512": "7e9ae5318fefbf76150aabad9f154a98fdee1b262c37859b3e1edff9920af11c62e79eb1434b2a77c22db304d0be01a8fac38f17a02931f595e893c089f98dbd",
          "sha256": "1824df0f2b3eb180d85b6a57cf8b1a97d8f161404998e3f3dc645d678c580cee",
          "sha1": "ba2d5ece6f7ee3e53eb7ed915228428fad9b4121",
          "md5": "9d5b4227dc59a591d0c7f515b056a55c"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-fabric-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.21.1-1.3.0-dev-shadow.jar",
          "url": "knightlib-fabric-1.21.1-1.3.0-dev-shadow.jar",
          "size": 409025,
          "sha512": "9af0468a53f8d4aaa54456b24e6c3d4c9a7e7677e9bffa6e8d23e01113d668027cd5e16723d5fb8d4f64fd4dd1add2c723656c46c4980bf95b5bce32a073f19f",
          "sha256": "e731b8cc7ed0fd96f1930d19cba83397fe267dec65421a6b6e40827a8b87c00b",
          "sha1": "20501a46d1114d0df86b35191b544b998953b69b",
          "md5": "f1ea41dde251eb245bf501ada16954bf"
        }
      ]
    }
  ]
}
