{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-fabric-1.21.1",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.21.1-1.3.0.jar",
          "url": "knightlib-fabric-1.21.1-1.3.0.jar",
          "size": 420091,
          "sha512": "f000a293e6bdd32df7ee1652d9780af7e6a5f73d9d336e029a6318d8c360ea6ca0ff9d12712bfa43f29ea99bb689309c6e2bf0fd2d85c2a0406eca3aa31a7396",
          "sha256": "37a42b678652b7afd3d470fa3f81bb19d6ae1a0060d76fc7b587b03310e004ab",
          "sha1": "f58a61b22adde13bdd2309b71d36728ae21df568",
          "md5": "7bb6307a4381165b67933591927380db"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-fabric-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-fabric-1.21.1",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.21.1.311"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.109.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.21.1-1.3.0.jar",
          "url": "knightlib-fabric-1.21.1-1.3.0.jar",
          "size": 420091,
          "sha512": "f000a293e6bdd32df7ee1652d9780af7e6a5f73d9d336e029a6318d8c360ea6ca0ff9d12712bfa43f29ea99bb689309c6e2bf0fd2d85c2a0406eca3aa31a7396",
          "sha256": "37a42b678652b7afd3d470fa3f81bb19d6ae1a0060d76fc7b587b03310e004ab",
          "sha1": "f58a61b22adde13bdd2309b71d36728ae21df568",
          "md5": "7bb6307a4381165b67933591927380db"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-fabric-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.21.1-1.3.0-sources.jar",
          "url": "knightlib-fabric-1.21.1-1.3.0-sources.jar",
          "size": 142465,
          "sha512": "545c51d67396564935106d98a0e7bb91cbcff55d95eb67b9f178910d27e2d8192529b4c1fb45f2b0c9aeff150a37354759a66b2506b64d2e749cb1d7ea2c0064",
          "sha256": "9def93db7256564d5479df87f9993c04da11388c4684bea5adf7ac7b481a83ad",
          "sha1": "244cffb361e17e492b1644a10d7157374f94d8cf",
          "md5": "4903aa8d2aefd97eee25fb3df93d6097"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-fabric-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.21.1-1.3.0-javadoc.jar",
          "url": "knightlib-fabric-1.21.1-1.3.0-javadoc.jar",
          "size": 435910,
          "sha512": "42a3f622c74fcdb11758d2830da053404936360d3bbf6f1396ee8b72fad93b882b8eb4cfebe8300f5b77c87bb2827ffd00125af28446027d69ff47044ac3dfde",
          "sha256": "e758922954a1561b0ac862954f59aa5a52fe17162260ba104a540632952509e3",
          "sha1": "a6c32ee2645895067e15328adf61a3b921675677",
          "md5": "cffa77a950161b9644a3e4f035a7fff3"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-fabric-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.21.1-1.3.0-dev-shadow.jar",
          "url": "knightlib-fabric-1.21.1-1.3.0-dev-shadow.jar",
          "size": 408860,
          "sha512": "6d854fb44cb67b1d194b9aedff3144271c2e4cac7d3fa9854024fa32a0abc1246bc6cffc8cdc3fbd77a6281df5f5af1d8596106bd33430c35d21a25a6c5f7980",
          "sha256": "e3d7f7bd4932364f05c548c453b11a589a67b8a2e45f6ecb08f5a501b7d52ed6",
          "sha1": "59104efbb61bbee47c75dc56580f4cc3604fdb4d",
          "md5": "09c68555d0397abdae1c04b664197d36"
        }
      ]
    }
  ]
}
