{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-fabric-1.21.1",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.21.1-1.3.0.jar",
          "url": "knightlib-fabric-1.21.1-1.3.0.jar",
          "size": 420127,
          "sha512": "341af55beec67698195a8a14dc5a176b1f3e91668c644563e175bc060b2a74c0205a8a466188a46f4b4699494181336461eb0737d1385787198be26735bf5371",
          "sha256": "b65157eb9bbb3778c8d3c3c6a4a34c9513778618d2fdf4209d7ddf92a527d67f",
          "sha1": "24cbc79840d89dcafcb216af85a1910cf649aa74",
          "md5": "f2a4ef2ead3af2586e076e1ab567a417"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-fabric-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-fabric-1.21.1",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.21.1.311"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.109.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.21.1-1.3.0.jar",
          "url": "knightlib-fabric-1.21.1-1.3.0.jar",
          "size": 420127,
          "sha512": "341af55beec67698195a8a14dc5a176b1f3e91668c644563e175bc060b2a74c0205a8a466188a46f4b4699494181336461eb0737d1385787198be26735bf5371",
          "sha256": "b65157eb9bbb3778c8d3c3c6a4a34c9513778618d2fdf4209d7ddf92a527d67f",
          "sha1": "24cbc79840d89dcafcb216af85a1910cf649aa74",
          "md5": "f2a4ef2ead3af2586e076e1ab567a417"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-fabric-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.21.1-1.3.0-sources.jar",
          "url": "knightlib-fabric-1.21.1-1.3.0-sources.jar",
          "size": 142542,
          "sha512": "243d56a946dbe9dbcef3715afac427e20802a41090d92bfdd83c3b9d769480fb86bc5c0b4eca6d5a592673a34888c7680f51099793cfd246fa75fea0401cdbc5",
          "sha256": "a21685af54766f73ed763049367e3fa1d8dacecd7af0f7b303ee1d269adb1ab6",
          "sha1": "0b9166d3c64e715ab48a3998b22884991df3781f",
          "md5": "8ff7fec72503ad86c87ca8b3cd0e90f1"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-fabric-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.21.1-1.3.0-javadoc.jar",
          "url": "knightlib-fabric-1.21.1-1.3.0-javadoc.jar",
          "size": 435910,
          "sha512": "42a3f622c74fcdb11758d2830da053404936360d3bbf6f1396ee8b72fad93b882b8eb4cfebe8300f5b77c87bb2827ffd00125af28446027d69ff47044ac3dfde",
          "sha256": "e758922954a1561b0ac862954f59aa5a52fe17162260ba104a540632952509e3",
          "sha1": "a6c32ee2645895067e15328adf61a3b921675677",
          "md5": "cffa77a950161b9644a3e4f035a7fff3"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-fabric-1.21.1",
          "version": "1.3.0"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.21.1-1.3.0-dev-shadow.jar",
          "url": "knightlib-fabric-1.21.1-1.3.0-dev-shadow.jar",
          "size": 408895,
          "sha512": "2b9d4a55dd478e6b7c410bbd3ed426716b494170c2acb367ce83efa933f59da0b68048181d8e7dfdb6c147a9324d402041103401468cd8a8556d361c702dc9b7",
          "sha256": "1f17b128a42bda167423a801dfdb7ab24a7dd602d0d97a0d9789ad64be3f3785",
          "sha1": "f514552be2ffe291712e98e5eeb75b3d53e5fadb",
          "md5": "81ed4048c01ae32d889770d377619a40"
        }
      ]
    }
  ]
}
