{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-fabric-1.20.1",
    "version": "1.5.0q",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.5.0q.jar",
          "url": "knightlib-fabric-1.20.1-1.5.0q.jar",
          "size": 704699,
          "sha512": "79da40c85ea1d061c0883a302a6babaf56c51bbf8093d37b2a346fa49a4a791b9321bda5903eeed0f8e707fc5a24059bd4b121671da04b14b68b3761b3f65ef3",
          "sha256": "ac5029d253557cb57f211c92b6aecc34184cdab643510ba1fb92fe308f06e917",
          "sha1": "d86421dbdb2976a454699df3d67e9768b89986f1",
          "md5": "56a44f9110a3796ec78064e37da90b69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.xylonity.knightlib",
          "module": "knightlib-common-1.20.1",
          "version": {
            "requires": "1.5.0q"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-fabric-1.20.1",
          "version": {
            "requires": "4.7.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.5.0q.jar",
          "url": "knightlib-fabric-1.20.1-1.5.0q.jar",
          "size": 704699,
          "sha512": "79da40c85ea1d061c0883a302a6babaf56c51bbf8093d37b2a346fa49a4a791b9321bda5903eeed0f8e707fc5a24059bd4b121671da04b14b68b3761b3f65ef3",
          "sha256": "ac5029d253557cb57f211c92b6aecc34184cdab643510ba1fb92fe308f06e917",
          "sha1": "d86421dbdb2976a454699df3d67e9768b89986f1",
          "md5": "56a44f9110a3796ec78064e37da90b69"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.5.0q-sources.jar",
          "url": "knightlib-fabric-1.20.1-1.5.0q-sources.jar",
          "size": 295292,
          "sha512": "07a405718175586d92d18e87e46ea6fa0d2996c691af2aefb062190dc6c0d2a0a8bb7391ac221e6d4e2f68459af738249c7b82076bc54a707eba7777bfd97f0a",
          "sha256": "d6b73a7d3c31c2d7ca33d59018daa6e80549b19fa107ae56008886a188ef5e1b",
          "sha1": "5c112902379dbd8f1060bbbf7dca6ab79492f29c",
          "md5": "3be925e359c9a172fa915304590bc85e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.5.0q-javadoc.jar",
          "url": "knightlib-fabric-1.20.1-1.5.0q-javadoc.jar",
          "size": 1052645,
          "sha512": "a13d895dd78f6da47d8dadf07f92b38db9d10fca82b2232157d638c9c90e9ac92d7e55ebe6baa62293a6bb1fa28646578889d6f43a48b514ea46380d48c1ecea",
          "sha256": "bd3e96aba82ae92c206f5f7996f89765c957ce5a2d809f4500efe16350450bbd",
          "sha1": "4d2e329667d35fb57c340baec9cc20b23b63d51b",
          "md5": "c59745cd0d7889afaa4d30d33ef1bcd9"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.5.0q-dev-shadow.jar",
          "url": "knightlib-fabric-1.20.1-1.5.0q-dev-shadow.jar",
          "size": 685942,
          "sha512": "8fbcb69cc701da6b112d5cb6d9c83ab26d904c5756349297c96ca94d9c451ccef73dce3303dfd5f23ec6772c15fad5bdb28b929442fe0cd584c1efde578cd2e6",
          "sha256": "7d61fe4c8b6a9b8f900d1377dda9a5502ec7d828a835367fd9dde56d71175e17",
          "sha1": "cf6482403238f2e9059b92aacd152d334e6e0e6c",
          "md5": "9f3249677b861d29bcd75cb66d77e729"
        }
      ]
    }
  ]
}
