{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.tooltipoverhaul",
    "module": "tooltipoverhaul-common-1.20.1",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-common-1.20.1-1.0.0-sources.jar",
          "url": "tooltipoverhaul-common-1.20.1-1.0.0-sources.jar",
          "size": 179921,
          "sha512": "1eb163e70e6c246c1a33e41406b42f9a4d748944151fb1839ca2a215fdf51368c96650998d0de91055de63a31935c79d1fc8de9d04cc78d4b032f86e7c5c35a7",
          "sha256": "61434f183f8408f7d4ec4757ecdf8d99058cdb53678bd324ed87601321e2cd29",
          "sha1": "8447f9746728e79254e223985fcc0167ce9a1db4",
          "md5": "2cefc8ce874f2c0d5bbabac86273e316"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-common-1.20.1",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "common",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-common-1.20.1-1.0.0-javadoc.jar",
          "url": "tooltipoverhaul-common-1.20.1-1.0.0-javadoc.jar",
          "size": 361765,
          "sha512": "b082770c004d3e237498738dc4b26e50684772ba255c7b00510c2905f72336c7939991dcf97607146c3f9abc0b0bc103672e051e94f8c6ac7b691ce30d265597",
          "sha256": "a9ba2eec35b3781930b5f0bee83dc356e0af054c5241931476c538c6d4adfd7c",
          "sha1": "6b9adcf8b45d13850170af1db4ae2df5ae570a93",
          "md5": "42c4c11179cf0f7e703524debd9b576d"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-common-1.20.1",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "common",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-common-1.20.1-1.0.0.jar",
          "url": "tooltipoverhaul-common-1.20.1-1.0.0.jar",
          "size": 249973,
          "sha512": "526bf35229b36686a34c626d33e18111daca11df787926aa37b68182552d9cbe5e21f4dd1cffa558121803ebeb004b0ee99ea19af664625484c37c8259a21107",
          "sha256": "345da5d9dc030721413da5511ea30c9399173470dbcddb1db5a67fd856ab6470",
          "sha1": "a28bf707a62ab280bb1f84ec6ada327e509ebe03",
          "md5": "8d66c7213c45d386f1db9b170443a72b"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tooltipoverhaul-common-1.20.1-1.0.0.jar",
          "url": "tooltipoverhaul-common-1.20.1-1.0.0.jar",
          "size": 249973,
          "sha512": "526bf35229b36686a34c626d33e18111daca11df787926aa37b68182552d9cbe5e21f4dd1cffa558121803ebeb004b0ee99ea19af664625484c37c8259a21107",
          "sha256": "345da5d9dc030721413da5511ea30c9399173470dbcddb1db5a67fd856ab6470",
          "sha1": "a28bf707a62ab280bb1f84ec6ada327e509ebe03",
          "md5": "8d66c7213c45d386f1db9b170443a72b"
        }
      ]
    }
  ]
}
