{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.tooltipoverhaul",
    "module": "tooltipoverhaul-forge-1.20.1",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-forge-1.20.1-1.0.0-sources.jar",
          "url": "tooltipoverhaul-forge-1.20.1-1.0.0-sources.jar",
          "size": 185687,
          "sha512": "68dfd5304008764019b2d547c783b2a3bcf6357e9ac05c9dcecf7d9904876621a5e78496b9a63308d6fed4573b431abcaa2c4ccfb37b0eaff80638ebc196b819",
          "sha256": "d7e0a878c441bfcf4acf86202d7556107e8c93fcc30fd28aa2d3d9246dacb9cf",
          "sha1": "b0cab334b25df7b888ac04193b365407ed9f4539",
          "md5": "79d3b619fb3a66a0b6440823c18db82f"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-forge-1.20.1",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "forge",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-forge-1.20.1-1.0.0-javadoc.jar",
          "url": "tooltipoverhaul-forge-1.20.1-1.0.0-javadoc.jar",
          "size": 376070,
          "sha512": "a64cc3c55669dfd8b8cf3fdf0161992f48a8f4f03c4f225826cf700d952e6a649cac63b80402dcff24538e9694a2946eb121e8bb2d675d4d8c637fca4ac73fff",
          "sha256": "73dfdd3ece247c272f54f801320b31bcc9ded8fa47c7a4bf10edf1b51ba47203",
          "sha1": "d5c2b5fc1df397d8f5eef816d829a59b866be611",
          "md5": "90f08e83b62aa973f0693f4f5b2ddd28"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul-forge-1.20.1",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "forge",
          "version": "1.0.0"
        },
        {
          "group": "dev.xylonity.tooltipoverhaul",
          "name": "tooltipoverhaul",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipoverhaul-forge-1.20.1-1.0.0.jar",
          "url": "tooltipoverhaul-forge-1.20.1-1.0.0.jar",
          "size": 262822,
          "sha512": "e2d641232b587e3648b29dc36747628ad845d8bfad2d7cf4c004874d9ce1da71cf9d697e0268f765dca9fd5660f554c29e1ca7e85bf1a6c2626ca744b2558978",
          "sha256": "5d02a2a4ba2364a23f88b6e1e4f1acbe16f1126ebe710e6ca0715fdc42ce3530",
          "sha1": "9dc340ef58e90ddf9575838ac57a4c920069b1dd",
          "md5": "60882a9f32929ee6e1dc5d310e6c6cda"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tooltipoverhaul-forge-1.20.1-1.0.0.jar",
          "url": "tooltipoverhaul-forge-1.20.1-1.0.0.jar",
          "size": 262822,
          "sha512": "e2d641232b587e3648b29dc36747628ad845d8bfad2d7cf4c004874d9ce1da71cf9d697e0268f765dca9fd5660f554c29e1ca7e85bf1a6c2626ca744b2558978",
          "sha256": "5d02a2a4ba2364a23f88b6e1e4f1acbe16f1126ebe710e6ca0715fdc42ce3530",
          "sha1": "9dc340ef58e90ddf9575838ac57a4c920069b1dd",
          "md5": "60882a9f32929ee6e1dc5d310e6c6cda"
        }
      ]
    }
  ]
}
