{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-common-1.21.1",
    "version": "1.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "knightlib-common-1.21.1-1.5.5.jar",
          "url": "knightlib-common-1.21.1-1.5.5.jar",
          "size": 530150,
          "sha512": "3214eabb2f9db4904666876aabf9ff8fa151784304c1568b97b42c917e2049705783aa050566864c625f00d3304d598f71232a6b646afd074edb143ffc494166",
          "sha256": "a445213fb14245d6cdc78aec73412607449486de868bfda8b778d83684a8e22f",
          "sha1": "9e8440f43032f5e93b13cc711f98985806b5cdc1",
          "md5": "dcc1ea5ecb0a12e9b623c88006efbf7d"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-common-1.21.1",
          "version": "1.5.5"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.5.5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.21.1-1.5.5.jar",
          "url": "knightlib-common-1.21.1-1.5.5.jar",
          "size": 530150,
          "sha512": "3214eabb2f9db4904666876aabf9ff8fa151784304c1568b97b42c917e2049705783aa050566864c625f00d3304d598f71232a6b646afd074edb143ffc494166",
          "sha256": "a445213fb14245d6cdc78aec73412607449486de868bfda8b778d83684a8e22f",
          "sha1": "9e8440f43032f5e93b13cc711f98985806b5cdc1",
          "md5": "dcc1ea5ecb0a12e9b623c88006efbf7d"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-common-1.21.1",
          "version": "1.5.5"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.5.5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.21.1-1.5.5-sources.jar",
          "url": "knightlib-common-1.21.1-1.5.5-sources.jar",
          "size": 320381,
          "sha512": "9da29c43be716094ffa348f3b308af7ce19ff9f4952623bb44c2c91d66eaeaf1dcf1f85afc150746318832c95b7c1f5563a2521b0088a8490b5d0f6852003d7f",
          "sha256": "b8506c11324591e14abd110d415476edd5223ce633eef5eba2c482750b106b3b",
          "sha1": "8706d70ffd67e4ebe69d56b45f724e8dc0a43730",
          "md5": "80d95514bf489f6f4b4944b918e9d2b6"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-common-1.21.1",
          "version": "1.5.5"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.5.5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-common-1.21.1-1.5.5-javadoc.jar",
          "url": "knightlib-common-1.21.1-1.5.5-javadoc.jar",
          "size": 1104806,
          "sha512": "4f1007e2a8af62bc2ef15f0d81ac01fbfbfe1fbb4eb06aa73d8342f4057cb043ef1519e571027e6dca436029a2802a5418264a99ea235cdb9bbdfb4fbc75f891",
          "sha256": "0215cbcfbc8556465cea88f7bec921d8efc1716f69a08e0beea26357abf4edc0",
          "sha1": "d9a9ce48c6eb29fca45c68cc72778e65bd24c3e0",
          "md5": "b9f4f29e16867be4177d8b21f776d775"
        }
      ],
      "capabilities": [
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib-common-1.21.1",
          "version": "1.5.5"
        },
        {
          "group": "dev.xylonity.knightlib",
          "name": "knightlib",
          "version": "1.5.5"
        }
      ]
    }
  ]
}
