{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-fabric-1.20.1",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.4.0.jar",
          "url": "knightlib-fabric-1.20.1-1.4.0.jar",
          "size": 472186,
          "sha512": "4a4cc4e87e408e5d433ec12e3132a1612a0a5768cd38681a53b0316d423760e8a814103ec31f60d75146c9af23b25bd22f27ac46f5d6225aaca26cc063ae809a",
          "sha256": "a3ece09eb02406be4969e23e2699e2e4db893ef70ef8567691927f3a88114978",
          "sha1": "bce7e808f4898860547274afd484c00ff2e36fea",
          "md5": "0b48fa5ab77066c942ff9231f117b0a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.xylonity.knightlib",
          "module": "knightlib-common-1.20.1",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-fabric-1.20.1",
          "version": {
            "requires": "4.7.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.4.0.jar",
          "url": "knightlib-fabric-1.20.1-1.4.0.jar",
          "size": 472186,
          "sha512": "4a4cc4e87e408e5d433ec12e3132a1612a0a5768cd38681a53b0316d423760e8a814103ec31f60d75146c9af23b25bd22f27ac46f5d6225aaca26cc063ae809a",
          "sha256": "a3ece09eb02406be4969e23e2699e2e4db893ef70ef8567691927f3a88114978",
          "sha1": "bce7e808f4898860547274afd484c00ff2e36fea",
          "md5": "0b48fa5ab77066c942ff9231f117b0a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.4.0-sources.jar",
          "url": "knightlib-fabric-1.20.1-1.4.0-sources.jar",
          "size": 172817,
          "sha512": "10d175e0a2a89bd3a691f8ed41b8742ccdf77caa2ef446ff015b8af094b317fc8e047effc8ca72e770baa316deb724437dd9798e26f26d52bad983eca429274f",
          "sha256": "c5d9ebc9ed2dcbfdccc720ec56b0b9060133e3cbfe103e246159ffdc6bd7d4b4",
          "sha1": "2b9e34faf3a55d5fe68006898a58febb1f4e6e1d",
          "md5": "3b8c0a3cfc9f0d865fc5630a82997f1d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.4.0-javadoc.jar",
          "url": "knightlib-fabric-1.20.1-1.4.0-javadoc.jar",
          "size": 547817,
          "sha512": "53eeeb6521cf09736de908754b42f63cbf87fc299f3d75c906d8796a1276a073678a6bc4d19dd8f40353221c8bee121369d1bb06813fa5e7c59fda53b084a21e",
          "sha256": "37b95c5886e545fc74b8c72347a5b757d841af527385fad5328899cb8877c116",
          "sha1": "c9e121515d813d87a99e27e64904231bd31435b7",
          "md5": "5a457eea59b45093b13b5d4fedf4f5cb"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.4.0-dev-shadow.jar",
          "url": "knightlib-fabric-1.20.1-1.4.0-dev-shadow.jar",
          "size": 459296,
          "sha512": "85eaaa3688c01dfbc9e1eb4bc885bb1d5f38392a5857d2ced3419b68ffb1cddaaa269bdd13adad23534c043afeb8da4579a9c73b919488253ae13ecc4759c796",
          "sha256": "d0d633ea1cd5113d68283c1331f988765f10396df345251942fef9d1a880651c",
          "sha1": "9e3c0b8553fae7af13c5a9654eb4dbb7688d57bc",
          "md5": "af5bb1459874b4f2b1100dfe53038632"
        }
      ]
    }
  ]
}
