{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.xylonity.knightlib",
    "module": "knightlib-fabric-1.20.1",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.4.0.jar",
          "url": "knightlib-fabric-1.20.1-1.4.0.jar",
          "size": 472188,
          "sha512": "d34c9f7000e36b982ff232f4e9cfcd77e0f85802cd9e9ef8d34395eff1b214ce62f6bac3317a4661fdd5d41b16aa267a7911f483d31a172ec300f02c6b2338ed",
          "sha256": "0526489e21aff3e38e4d38df58a7bde03a2b64dff9b7c1265d42fddebd90939a",
          "sha1": "6c82828e3a73952f0a8597c3d223d51f6ad9b7c0",
          "md5": "894348524026303f88abba9c59a212db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.xylonity.knightlib",
          "module": "knightlib-common-1.20.1",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-fabric-1.20.1",
          "version": {
            "requires": "4.7.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.4.0.jar",
          "url": "knightlib-fabric-1.20.1-1.4.0.jar",
          "size": 472188,
          "sha512": "d34c9f7000e36b982ff232f4e9cfcd77e0f85802cd9e9ef8d34395eff1b214ce62f6bac3317a4661fdd5d41b16aa267a7911f483d31a172ec300f02c6b2338ed",
          "sha256": "0526489e21aff3e38e4d38df58a7bde03a2b64dff9b7c1265d42fddebd90939a",
          "sha1": "6c82828e3a73952f0a8597c3d223d51f6ad9b7c0",
          "md5": "894348524026303f88abba9c59a212db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.4.0-sources.jar",
          "url": "knightlib-fabric-1.20.1-1.4.0-sources.jar",
          "size": 172817,
          "sha512": "61b2a29b668e9975aa23e266b7b20fcc4d27bbd5cb9dda03b1965fe06bc3305cd1f5d501c6edce6a3d8681e753c70bd5cc94f705fe43a65394cdda560f0b18c7",
          "sha256": "3e107fb6ef368dba0a7525b096d40f75601b37d6afc84a4b59e8a30ce594dba9",
          "sha1": "c759cf880ee0ec7ee47c5ce9eda08f1b7c0dfbb0",
          "md5": "08234ab1de7f580e9c473325d9820de4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.4.0-javadoc.jar",
          "url": "knightlib-fabric-1.20.1-1.4.0-javadoc.jar",
          "size": 547817,
          "sha512": "53eeeb6521cf09736de908754b42f63cbf87fc299f3d75c906d8796a1276a073678a6bc4d19dd8f40353221c8bee121369d1bb06813fa5e7c59fda53b084a21e",
          "sha256": "37b95c5886e545fc74b8c72347a5b757d841af527385fad5328899cb8877c116",
          "sha1": "c9e121515d813d87a99e27e64904231bd31435b7",
          "md5": "5a457eea59b45093b13b5d4fedf4f5cb"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "knightlib-fabric-1.20.1-1.4.0-dev-shadow.jar",
          "url": "knightlib-fabric-1.20.1-1.4.0-dev-shadow.jar",
          "size": 459297,
          "sha512": "bf7b9de673fba4becbe2d4618fb0688b5317b39958ded0a5debb0a3693a2f2bec5df9ef76dd89dad56a18f2655bcc84947e94054d8688764668de178f7e12ebf",
          "sha256": "3a9a375d6a3440e44ec579936c4f72706a26f1458ce6e9fed9f0ecf8b0a26518",
          "sha1": "932b0d176d4b84afba01f2afa6cdaa226787ea47",
          "md5": "0d478cedf1ac62a61991c5921518f5f8"
        }
      ]
    }
  ]
}
